import * as C from './core.js';
const $=s=>document.querySelector(s),app=$('#app'),modal=$('#modal');
const SAVE='sam_paep_run_v1',PREF='sam_paep_pref_v1';let run=null,battle=null,game=null,scene=null,saved=null,sound=false,audio=null,speed=1,paused=false,slot=0,toastTimer;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
try{const s=JSON.parse(localStorage.getItem(SAVE));if(C.validSave(s))saved=s;sound=JSON.parse(localStorage.getItem(PREF))?.sound===true;}catch{}
const esc=s=>String(s).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
function toast(text){$('#toast').textContent=text;$('#toast').style.opacity=1;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.opacity=0,2500);}
function save(){if(!run)return;try{localStorage.setItem(SAVE,JSON.stringify(run));saved=structuredClone(run);}catch{toast('이 브라우저에서 저장할 수 없습니다. 창을 닫으면 진행이 사라집니다.');}}
function beep(skill=false){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=skill?'triangle':'sine';o.frequency.setValueAtTime(skill?480:180,audio.currentTime);o.frequency.exponentialRampToValueAtTime(skill?160:70,audio.currentTime+.16);g.gain.setValueAtTime(.07,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.23);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.25);}catch{}}
function portrait(o,cls='portrait'){return o.image?`<img class="${cls}" src="${esc(o.image)}" alt="${esc(o.name)}" loading="lazy">`:`<div class="${cls} portrait-fallback">${esc(o.name)}</div>`;}
function btn(text,action,extra='',cls=''){return `<button class="${cls}" data-action="${action}" ${extra}>${text}</button>`;}
function officerCard(name,index=null,action='detail'){const o=C.officer(name),r=run?.roster.find(r=>r.name===name)||{level:1,hp:1};return `<button class="officer ${C.UNIQUE[name]?'legend':''}" data-action="${action}" data-name="${esc(name)}">${portrait(o)}${index!==null?`<span class="position">${index<2?'전열':'후열'} ${index+1}</span>`:''}<div class="info"><span class="meta">${o.faction} · ${C.ROLES[C.roleOf(o)]} · Lv.${r.level}</span><strong class="name">${name}</strong><div class="hp"><span style="width:${r.hp*100}%"></span></div><span class="skill-label">${C.skillOf(o)[0]}</span></div></button>`;}
function top(label){return `<div class="run-top"><div><div class="eyebrow">${label}</div><h1>${C.CHAPTERS[run.stage]||'천하평정'}</h1></div><div class="resources"><span>금 <b>${run.gold}</b></span><span>전승 <b>${run.wins}</b></span></div></div>`;}
function openModal(html){$('#modal-content').innerHTML=html;if(!modal.open)modal.showModal();}
$('#modal .close').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal)modal.close();});
$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'음향 켜짐':'음향 꺼짐';try{localStorage.setItem(PREF,JSON.stringify({sound}));}catch{}beep(true);};$('#sound').textContent=sound?'음향 켜짐':'음향 꺼짐';
$('#help').onclick=()=>openModal(`<div class="eyebrow">원정 안내</div><h2>다섯 장수로, 천하를 향해</h2><p>아홉 지역을 돌파하고 마지막 호로관에서 여포를 격파하세요. 전열 두 명이 기본 공격을 먼저 받고, 후열 세 명은 책략과 지원을 담당합니다.</p><ul><li><b>전투:</b> 일반 공격은 자동입니다. 기력이 100이면 고유기가 발동합니다. ‘자동기’를 끄면 아래 장수 버튼으로 다음 행동의 스킬을 예약할 수 있습니다.</li><li><b>전술:</b> 전투마다 3회 사용합니다. 치유는 전군 체력 24% 회복, 방어는 보호막 100, 집중은 아군 8회 행동 동안 약한 적을 우선 공격합니다.</li><li><b>인연:</b> 기존 장수 인연을 재사용합니다. 출전 장수 사이에 완성된 인연 하나당 공격력 +3%, 최대 +15%입니다.</li><li><b>원정:</b> 승리하면 쓰러진 장수도 복귀하고 체력을 일부 회복합니다. 야영지에서 완전 회복하거나 인재를 영입할 수 있습니다.</li><li><b>편성:</b> 야영·원정 화면에서 자유롭게 교체합니다. 강화는 금 60, 최대 5레벨입니다. 보물 효과는 전군에 적용됩니다.</li><li><b>저장:</b> 이 기기의 브라우저에 자동 저장합니다. 전투 중 다시 열면 해당 전투 시작부터 재개합니다. 250회 행동 내 승리하지 못하면 원정이 종료됩니다.</li></ul><p>모든 장수가 네 원본 능력치를 전투 능력치로 변환해 사용합니다. 이 게임의 강화와 기록은 기존 드래프트 게임과 별개입니다.</p>`);
function destroyBattle(){if(game){game.destroy(true);game=null;}scene=null;battle=null;}
function home(){destroyBattle();app.innerHTML=`<div class="intro"><div><div class="eyebrow">三國志 · 원정 전략</div><h1>어느 깃발 아래<br>천하를 시작하겠습니까.</h1></div><p>다섯 장수의 인연, 한 번의 전술.<br>장수를 모으고 부대를 성장시켜 호로관에 도전하세요.</p></div>${saved&&!['victory','defeat'].includes(saved.phase)?`<div class="resume"><div><strong>진행 중인 ${saved.faction}군 원정</strong><p>${saved.stage+1} / 9 지역 · ${saved.wins}승 · 금 ${saved.gold}</p></div>${btn('이어하기','resume','','primary')}</div>`:''}<div class="start-grid">${[['촉','유비','蜀','인연으로 뭉치는 군세','유비의 회복과 관우의 일격. 전열과 지원이 균형 잡힌 출발.'],['위','조조','魏','전술로 압도하는 군세','조조의 기력 지원과 장료의 도발. 빠른 고유기 순환.'],['오','손권','吳','화염으로 전장을 지배','손권의 지휘와 주유의 화공. 적 전군을 태우는 책략.']].map(([f,n,h,t,d])=>`<article class="kingdom">${portrait(C.officer(n),'cover')}<div class="faction-mark">${h}</div><div class="content"><span class="badge">${t}</span><h2>${n}의 ${f}군</h2><p>${d}</p>${btn(f+'군으로 출정','start',`data-faction="${f}"`,'primary')}</div></article>`).join('')}</div><div class="intro-foot"><span>279명 장수 · 23개 고유기 · 9개 원정 지역</span><span>전투와 원정은 이 기기에 자동 저장됩니다.</span></div>`;}
function map(){const bonds=C.bondsFor(run.lineup),sum=run.lineup.map(n=>C.stats(C.officer(n),run.roster.find(r=>r.name===n).level,run.relics));app.innerHTML=top('원정 '+(run.stage+1)+' / 9')+`<div class="layout"><section><div class="route-track">${C.CHAPTERS.map((c,i)=>`<div class="route-stop ${i<run.stage?'done':i===run.stage?'current':''}"><b><span>${i<run.stage?'✓':i+1}</span></b><span class="label">${['황건','영천','양양','사수','낙양','허창','관도','적벽','호로'][i]}</span></div>`).join('')}</div><div class="squad-header"><h3>다음 행군을 선택하십시오</h3><span class="badge">${run.faction}군</span></div><div class="routes">${C.nodesFor(run).map(n=>`<button class="route ${n.type}" data-action="node" data-type="${n.type}"><span class="icon">${{battle:'戰',elite:'襲',camp:'營',recruit:'賢',boss:'霸'}[n.type]}</span><strong>${n.title}</strong><small>${n.desc}</small></button>`).join('')}</div><div class="squad-header"><h3>출전 부대</h3>${btn('편성 · 강화','formation','','small')}</div><div class="squad">${run.lineup.map((n,i)=>officerCard(n,i)).join('')}</div><p class="section-note">전열 2명 · 후열 3명 — 장수를 누르면 능력과 고유기를 확인합니다.</p></section><aside class="side-stack"><section class="panel"><div class="eyebrow">結義</div><h3>함께할 때 강해진다</h3>${bonds.length?bonds.slice(0,5).map(b=>`<div class="bond"><b>${b.n}</b><small>${b.m.filter(n=>run.lineup.includes(n)).join(' · ')}</small></div>`).join(''):'<p class="empty">인연 장수 두 명 이상을 함께 편성하면 전군 공격력이 증가합니다.</p>'}<p class="section-note">인연 공격력 +${Math.min(15,bonds.length*3)}%</p></section><section class="panel"><h3>군세 현황</h3><div class="team-summary">보유 장수<b>${run.roster.length}명</b></div><div class="team-summary">출전 평균 레벨<b>${(run.lineup.reduce((v,n)=>v+run.roster.find(r=>r.name===n).level,0)/5).toFixed(1)}</b></div><div class="team-summary">전군 최대 체력<b>${sum.reduce((v,s)=>v+s.maxHp,0)}</b></div><div class="relics">${run.relics.map(id=>`<span class="relic" title="${C.RELICS.find(r=>r.id===id).desc}">${C.RELICS.find(r=>r.id===id).name}</span>`).join('')||'<span class="empty">획득한 보물 없음</span>'}</div><p class="save-note">자동 저장됨 · 전투마다 전술 3회</p></section>${btn('시작 화면','home','','small')}</aside></div>`;}
function detail(name){const o=C.officer(name),r=run?.roster.find(r=>r.name===name)||{level:1},st=C.stats(o,r.level,run?.relics||[]),sk=C.skillOf(o);openModal(`<div class="detail">${portrait(o)}<div><div class="eyebrow">${o.faction} · ${C.rarity(o)} · ${C.ROLES[C.roleOf(o)]}</div><h2>${name} <span class="badge">Lv.${r.level}</span></h2><div class="stat-grid">${[['통솔',o.command],['무력',o.might],['지력',o.intellect],['정치',o.politics]].map(([k,v])=>`<div>${k}<b>${v}</b></div>`).join('')}</div><p class="section-note">체력 ${st.maxHp} · 공격 ${st.attack} · 방어 ${st.defense}</p></div><div class="detail-skill"><b>${C.UNIQUE[name]?'고유기':'역할기'} · ${sk[0]}</b><p>${sk[3]}</p></div></div>`);}
function formation(){openModal(`<div class="eyebrow">부대 편성</div><h2>앞에서 버티고, 뒤에서 지원한다</h2><p>교체할 자리를 고른 뒤 장수를 누르세요. 출전 중인 장수를 고르면 두 자리가 바뀝니다.</p><div class="slot-select">${run.lineup.map((n,i)=>btn(`${i<2?'전열':'후열'} ${n}`,'slot',`data-slot="${i}"`,i===slot?'selected':'')).join('')}</div><div class="bench">${run.roster.map(r=>officerCard(r.name,null,'assign')).join('')}</div><h3 style="margin-top:24px">장수 강화 · 금 ${run.gold}</h3><div class="slot-select">${run.roster.map(r=>btn(`${r.name} Lv.${r.level} → ${r.level<5?'강화 60':'최대'}`,'upgrade',`data-name="${r.name}" ${run.gold<60||r.level>=5?'disabled':''}`,'small')).join('')}</div>`);}
function reward(){app.innerHTML=`<section class="result"><div class="eyebrow">${C.CHAPTERS[run.stage]} · 승전</div><div class="result-mark">勝</div><h1>승리를 다음 전력으로.</h1><p>금 ${run.selectedNode==='elite'?100:60} 획득 · 전군 체력 일부 회복<br>원정 끝까지 함께할 보물을 하나 고르세요.</p><div class="reward-grid">${run.offers.map(id=>{const r=C.RELICS.find(r=>r.id===id);return `<button class="reward-card" data-action="reward" data-id="${id}"><span>${r.symbol}</span><strong>${r.name}</strong><small>${r.desc}</small></button>`;}).join('')}</div>${btn('대신 금 70 획득','reward','data-id="gold"')}<p class="save-note">이미 가진 보물은 다시 나오지 않습니다.</p></section>`;}
function recruitment(){app.innerHTML=`<section class="result"><div class="eyebrow">재야의 인재</div><h1>함께 길을 열 장수.</h1><p>한 명을 무료로 영입합니다. 영입한 장수는 편성에서 교체할 수 있습니다.</p><div class="recruit-grid">${run.offers.map(n=>{const o=C.officer(n),sk=C.skillOf(o);return `<article class="officer ${C.UNIQUE[n]?'legend':''}">${portrait(o)}<div class="info"><span class="meta">${o.faction} · ${C.rarity(o)} · ${C.ROLES[C.roleOf(o)]}</span><strong class="name">${n}</strong><span class="skill-label">${sk[0]}</span><p class="section-note">${sk[3]}</p>${btn('영입','recruit',`data-name="${n}"`,'primary')}</div></article>`;}).join('')}</div></section>`;}
function camp(){app.innerHTML=`<section class="result"><div class="eyebrow">야영지</div><div class="result-mark">營</div><h1>다음 전투를 준비하다.</h1><p>모든 장수가 완전히 회복했습니다.<br>장수 한 명을 무료로 강화하세요.</p><div class="camp-list">${run.roster.map(r=>officerCard(r.name,null,'camp-upgrade')).join('')}</div>${btn('강화 없이 행군','camp-skip')}</section>`;}
function ending(){const win=run.phase==='victory';app.innerHTML=`<section class="result"><div class="eyebrow">${win?'원정 완수':'원정 종료'}</div><div class="result-mark">${win?'天下':'敗'}</div><h1>${win?'천하에 당신의 깃발을.':'다음 원정에는, 다른 길을.'}</h1><p>${win?'호로관을 돌파하고 패업의 길을 완수했습니다.':'부대가 더 이상 진군할 수 없습니다. 회복·방어 역할과 전술을 활용해 다시 도전하세요.'}<br>${run.faction}군 · ${run.wins}승 · 보물 ${run.relics.length}개 · 금 ${run.gold}</p><div class="squad">${run.lineup.map((n,i)=>officerCard(n,i)).join('')}</div><div class="bottom-actions">${btn('새 원정 시작','home','','primary')}</div></section>`;}
function render(){if(run.phase!=='battle')destroyBattle();switch(run.phase){case'map':map();break;case'battle':startBattle();break;case'reward':reward();break;case'recruit':recruitment();break;case'camp':camp();break;default:ending();}window.scrollTo({top:0,behavior:'instant'});}
function skillButtons(){if(!battle)return;$('#skills').innerHTML=battle.units.filter(u=>u.side==='ally').map(u=>`<button class="skill-button ${u.energy>=100&&u.hp>0?'ready':''}" data-action="skill" data-key="${u.key}" ${u.energy<100||u.hp<=0?'disabled':''}><strong>${u.name}</strong><small>${u.hp<=0?'전투 불능':battle.queue.includes(u.key)?'발동 예약':C.skillOf(u)[0]}</small><div class="energy"><span style="width:${u.energy}%"></span></div></button>`).join('');$('#commands-left').textContent=battle.commands;document.querySelectorAll('[data-action="command"]').forEach(el=>el.disabled=battle.commands<=0||!!battle.ended);$('#turn-label').textContent='행동 '+battle.turn+' / 250';}
function startBattle(){if(game)return;paused=false;speed=1;battle=C.makeBattle(run);app.innerHTML=`<div class="battle-page">${top('전투 · '+(run.selectedNode==='boss'?'최종 결전':run.selectedNode==='elite'?'정예군':'일반군'))}<section class="battle-shell"><div class="battle-heading"><div><h2>전장을 지휘하십시오</h2><span class="badge" id="turn-label">행동 0 / 250</span></div><div class="battle-tools">${btn('자동기 켜짐','auto')}${btn('1×','speed')}${btn('일시정지','pause')}</div></div><div id="battle-canvas" role="img" aria-label="아군 다섯 명과 적군 다섯 명의 전투 화면"></div><div class="combat-strip" id="skills"></div></section><div class="commands"><p>전술 <b id="commands-left">3</b>회 남음 · 기본 공격은 자동</p><div class="command-buttons">${btn('치유 24%','command','data-type="heal"')}${btn('방어 +100','command','data-type="guard"')}${btn('집중 공격','command','data-type="focus"')}</div></div><div class="battle-log" aria-live="polite"><span>전황</span><b id="battle-message">진형을 갖추는 중…</b></div><p class="section-note">자동기를 끄면 기력이 찬 장수를 눌러 고유기를 예약합니다. 전술은 일시정지 중에도 사용할 수 있습니다.</p></div>`;skillButtons();if(!window.Phaser){$('#battle-message').textContent='전투 엔진을 불러오지 못했습니다. 새로고침하면 같은 전투부터 이어집니다.';return;}const mobile=innerWidth<=560;game=new Phaser.Game({type:Phaser.AUTO,parent:'battle-canvas',width:mobile?640:1100,height:mobile?720:520,backgroundColor:'#0e1c24',scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},render:{antialias:true},audio:{noAudio:true},scene:class extends Phaser.Scene{
 preload(){for(const u of battle.units)if(u.image)this.load.image(u.key,u.image);}
 create(){scene=this;this.views={};this.clock=0;this.started=false;const W=this.scale.width,H=this.scale.height;
 const grid=this.add.graphics();grid.lineStyle(1,0x43606a,.15);for(let x=0;x<W;x+=45)grid.lineBetween(x,0,x,H);for(let y=0;y<H;y+=45)grid.lineBetween(0,y,W,y);grid.lineStyle(1,0xb79352,.24);grid.strokeCircle(W/2,H/2,Math.min(W,H)*.3);grid.strokeCircle(W/2,H/2,Math.min(W,H)*.23);
 this.add.text(W/2,H/2,'對 陣',{fontFamily:'serif',fontSize:mobile?'40px':'48px',color:'#60747a'}).setOrigin(.5).setAlpha(.22);
 this.add.text(mobile?24:W-30,mobile?15:18,'敵 軍',{fontFamily:'serif',fontSize:'20px',color:'#db907c'}).setOrigin(mobile?0:1,0);this.add.text(mobile?24:30,mobile?H-34:18,'我 軍',{fontFamily:'serif',fontSize:'20px',color:'#76d2c6'});
 for(const u of battle.units){const ally=u.side==='ally',front=u.index<2,i=front?u.index:u.index-2;let x,y;
 if(mobile){x=front?230+i*180:150+i*170;y=ally?(front?447:604):(front?270:113);}else{x=ally?(front?385:190):(front?715:910);y=front?165+i*190:90+i*170;}
 const cw=mobile?116:128,ch=mobile?140:146,container=this.add.container(x,y),bg=this.add.rectangle(0,0,cw,ch,0x162a32).setStrokeStyle(1,C.UNIQUE[u.name]?0xb89654:0x48616c);container.add(bg);
 if(this.textures.exists(u.key)){const img=this.add.image(-(cw-8)/2,-ch/2+4,u.key).setOrigin(0,0);const scale=Math.max((cw-8)/img.width,94/img.height);img.setCrop(0,0,(cw-8)/scale,94/scale).setScale(scale);container.add(img);}
 else container.add(this.add.text(0,-20,u.name,{fontFamily:'serif',fontSize:'26px',color:'#d3bd8f'}).setOrigin(.5));
 const name=this.add.text(0,38,u.name,{fontFamily:'sans-serif',fontSize:mobile?'20px':'18px',fontStyle:'bold',color:'#eee8d9'}).setOrigin(.5);container.add(name);
 const hpBg=this.add.rectangle(0,ch/2-9,cw-10,5,0x563c3b),hp=this.add.rectangle(-(cw-10)/2,ch/2-9,cw-10,5,ally?0x6dccbd:0xe08a75).setOrigin(0,.5);container.add([hpBg,hp]);
 const hpText=this.add.text(0,ch/2+12,'',{fontFamily:'sans-serif',fontSize:'13px',color:'#b7c7c7'}).setOrigin(.5);container.add(hpText);
 const status=this.add.text(cw/2-3,-ch/2+3,'',{fontFamily:'sans-serif',fontSize:'12px',backgroundColor:'#11202be6',color:'#eed49b'}).setOrigin(1,0);container.add(status);
 this.views[u.key]={container,hp,hpText,bg,status,cw,x,y};}
 this.sync();this.time.delayedCall(600,()=>{this.started=true;$('#battle-message').textContent=battle.bonds.length?'인연 발동 · '+battle.bonds.slice(0,3).join(' / '):'양군이 맞붙었습니다.';});
 }
 sync(){for(const u of battle.units){const v=this.views[u.key];v.hp.width=(v.cw-10)*Math.max(0,u.hp/u.maxHp);v.hpText.setText(Math.max(0,u.hp)+' / '+u.maxHp);v.container.setAlpha(u.hp>0?1:.25);v.status.setText(u.hp<=0?'패퇴':u.stun?'봉쇄':u.burn?'화상':u.shield?'방어 '+u.shield:u.energy>=100?'고유기 준비':'');}}
 fx(ev){if(!ev)return;beep(ev.skill);const W=this.scale.width,H=this.scale.height,actor=ev.actor?this.views[ev.actor]:null;if(actor&&!reduced){this.tweens.add({targets:actor.bg,alpha:.35,duration:95,yoyo:true,repeat:1});}
 if(ev.skill){const band=this.add.rectangle(W/2,H/2,W,70,0x09151c,.94).setDepth(20);const t=this.add.text(W/2,H/2,ev.title,{fontFamily:'serif',fontSize:mobile?'29px':'30px',color:'#efd092'}).setOrigin(.5).setDepth(21);this.tweens.add({targets:[band,t],alpha:0,delay:reduced?200:520,duration:180,onComplete:()=>{band.destroy();t.destroy();}});if(!reduced)this.cameras.main.shake(100,.002);}
 for(const e of ev.events){const v=this.views[e.target],color=e.kind==='heal'?0x74e2c1:e.kind==='shield'?0x87bbeb:e.kind==='energy'?0xead095:ev.skill?0xf3b561:0xf6e4b9;
 if(!reduced&&actor&&['damage','burn'].includes(e.kind)){const line=this.add.graphics().setDepth(9);line.lineStyle(ev.skill?5:2,color,.9);line.lineBetween(actor.x,actor.y,v.x,v.y);this.tweens.add({targets:line,alpha:0,duration:200,onComplete:()=>line.destroy()});}
 if(!reduced){for(let i=0;i<(ev.skill?12:5);i++){const dot=this.add.circle(v.x,v.y,ev.skill?3:2,color).setDepth(10);const a=Math.random()*Math.PI*2,dist=30+Math.random()*45;this.tweens.add({targets:dot,x:v.x+Math.cos(a)*dist,y:v.y+Math.sin(a)*dist,alpha:0,duration:350,onComplete:()=>dot.destroy()});}}
 const text=this.add.text(v.x,v.y-20,(e.kind==='damage'||e.kind==='burn'?'-':'+')+e.amount+(e.critical?'!':''),{fontFamily:'sans-serif',fontSize:e.critical?'29px':'23px',fontStyle:'bold',color:'#'+color.toString(16),stroke:'#0c1720',strokeThickness:4}).setOrigin(.5).setDepth(15);this.tweens.add({targets:text,y:v.y-(reduced?20:55),alpha:0,delay:150,duration:400,onComplete:()=>text.destroy()});}
 this.sync();skillButtons();$('#battle-message').textContent=ev.title||'화상으로 전투 불능';}
 update(_,delta){if(!this.started||paused||modal.open||!battle||battle.ended)return;this.clock+=Math.min(delta,80)*speed;if(this.clock<820)return;this.clock=0;const ev=C.stepBattle(battle);this.fx(ev);if(battle.ended){const result=battle.ended;$('#battle-message').textContent=result==='win'?'승리했습니다. 전리품을 정리합니다.':'부대가 패퇴했습니다.';this.time.delayedCall(1100,()=>{C.finishBattle(run,battle);save();render();});}}
 }});}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action,n=el.dataset.name;
 if(a==='start'){if(saved&&!['victory','defeat'].includes(saved.phase)){openModal(`<h2>새 원정을 시작할까요?</h2><p>현재 원정의 이 기기 저장 기록이 새 원정으로 바뀝니다.</p>${btn('새 원정 시작','confirm-start',`data-faction="${el.dataset.faction}"`,'primary')}`);return;}begin(el.dataset.faction);return;}
 if(a==='confirm-start'){modal.close();begin(el.dataset.faction);return;}if(a==='resume'){run=structuredClone(saved);render();return;}if(a==='home'){home();return;}if(a==='detail'){detail(n);return;}
 if(!run)return;
 if(a==='node'&&C.chooseNode(run,el.dataset.type)){save();render();}else if(a==='formation'){slot=0;formation();}else if(a==='slot'){slot=Number(el.dataset.slot);formation();}else if(a==='assign'){C.swap(run,slot,n);save();map();formation();}else if(a==='upgrade'){if(C.upgrade(run,n)){save();map();formation();}}else if(a==='reward'){if(C.takeReward(run,el.dataset.id)){save();render();}}else if(a==='recruit'){if(C.recruit(run,n)){C.nextStage(run);save();render();toast(n+' 영입 · 편성에서 출전시킬 수 있습니다.');}}else if(a==='camp-upgrade'){if(C.upgrade(run,n,true)){C.nextStage(run);save();render();}else toast('이미 최대 레벨입니다. 다른 장수를 선택하세요.');}else if(a==='camp-skip'){C.nextStage(run);save();render();}
 else if(a==='pause'){paused=!paused;el.textContent=paused?'계속하기':'일시정지';}else if(a==='speed'){speed=speed===1?2:1;el.textContent=speed+'×';}else if(a==='auto'){battle.auto=!battle.auto;el.textContent=battle.auto?'자동기 켜짐':'자동기 꺼짐';}else if(a==='skill'){if(C.queueSkill(battle,el.dataset.key)){skillButtons();toast('다음 행동에 고유기를 발동합니다.');}}else if(a==='command'){scene?.fx(C.command(battle,el.dataset.type));}
});
function begin(faction){run=C.newRun(faction);save();render();}
if(document.modelContext?.registerTool){const lifecycle=new AbortController();addEventListener('pagehide',()=>lifecycle.abort(),{once:true});for(const tool of [
 {name:'read_expedition',description:'현재 원정과 전투 상태를 조회합니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return run?{phase:run.phase,stage:run.stage+1,faction:run.faction,gold:run.gold,lineup:run.lineup,battle:battle?{turn:battle.turn,commands:battle.commands,units:battle.units.map(u=>({name:u.name,side:u.side,hp:u.hp,maxHp:u.maxHp}))}:null}:{phase:'start'};}},
 {name:'use_battle_tactic',description:'진행 중인 전투에서 전술 1회를 소비하여 치유·방어·집중 공격을 적용합니다.',inputSchema:{type:'object',properties:{type:{type:'string',enum:['heal','guard','focus']}},required:['type'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!['heal','guard','focus'].includes(input.type)||!battle||!scene)throw Error('사용 가능한 전투와 전술이 필요합니다.');const ev=C.command(battle,input.type);if(!ev)throw Error('전술을 사용할 수 없습니다.');scene.fx(ev);return {commandsRemaining:battle.commands,tactic:input.type};}}
 ]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}}
home();
