import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as C from '../core.js';
test('all source officers have usable stats and skills; portraits exist',()=>{assert.equal(C.OFFICERS.length,279);assert.equal(new Set(C.OFFICERS.map(o=>o.name)).size,279);for(const o of C.OFFICERS){const s=C.stats(o);assert(s.maxHp>0&&s.attack>0&&s.speed>0);assert(C.skillOf(o).length===4);if(o.image)assert(fs.existsSync(new URL('../'+o.image,import.meta.url)));}});
test('unique effects: heal, shields, control and penetration change real state',()=>{for(const [name,type] of [['유비','heal'],['전위','shield'],['제갈량','control'],['관우','damage']]){const s=C.newRun('촉',42);s.lineup[0]=name;s.roster[0]={name,level:1,hp:1};s.selectedNode='battle';const b=C.makeBattle(s),u=b.units[0];b.units.forEach(x=>x.next=5);u.next=0;u.energy=100;b.units.filter(x=>x.side==='ally').forEach(x=>x.hp=Math.round(x.maxHp*.5));const ev=C.stepBattle(b);assert(ev.skill);if(type==='control')assert(b.units.filter(x=>x.side==='enemy').every(x=>x.stun===1));else assert(ev.events.some(e=>e.kind===type));}});
test('formation, paid upgrades, recruitment and commands reject invalid/repeated actions',()=>{const s=C.newRun('촉',4);assert(!C.swap(s,8,'유비'));assert(!C.swap(s,0,'unknown'));assert(C.swap(s,0,'관우'));assert.equal(s.lineup[1],'유비');assert(C.upgrade(s,'유비'));assert(!C.upgrade(s,'유비'));assert.equal(s.gold,40);C.chooseNode(s,'battle');const b=C.makeBattle(s);for(let i=0;i<3;i++)assert(C.command(b,'heal'));assert.equal(C.command(b,'guard'),null);assert.equal(C.queueSkill(b,'enemy-0'),false);assert.equal(C.chooseNode(s,'battle'),false);});
test('save validation and deterministic battle restart',()=>{const s=C.newRun('위',123);C.chooseNode(s,'elite');const saved=JSON.parse(JSON.stringify(s));assert(C.validSave(saved));assert.deepEqual(C.makeBattle(saved),C.makeBattle(s));assert(!C.validSave({...s,lineup:['유비']}));assert(!C.validSave({...s,roster:[{name:'no',level:1,hp:1}]}));});
function play(seed,faction,elite=false){const s=C.newRun(faction,seed);let guard=0;while(!['victory','defeat'].includes(s.phase)&&guard++<80){assert(C.validSave(s));if(s.phase==='map'){for(const n of s.lineup)if(s.gold>=60)C.upgrade(s,n);const nodes=C.nodesFor(s);C.chooseNode(s,nodes.some(n=>n.type==='camp')?'camp':nodes.some(n=>n.type==='boss')?'boss':elite?'elite':'battle');}else if(s.phase==='camp'){const n=[...s.roster].sort((a,b)=>a.level-b.level)[0].name;C.upgrade(s,n,true);C.nextStage(s);}else if(s.phase==='recruit'){C.recruit(s,s.offers[0]);C.nextStage(s);}else if(s.phase==='reward'){assert(C.takeReward(s,s.offers[0]||'gold'));assert(!C.takeReward(s,'bad'));}else if(s.phase==='battle'){const b=C.makeBattle(s);while(!b.ended){if(b.commands>0&&C.living(b,'ally').some(u=>u.hp/u.maxHp<.5))C.command(b,'heal');C.stepBattle(b);assert(b.units.every(u=>Number.isFinite(u.hp)&&u.hp>=0&&u.hp<=u.maxHp&&u.shield>=0));}assert(C.finishBattle(s,b));assert(!C.finishBattle(s,b));}}assert(guard<80);return s.phase;}
test('full campaigns terminate safely across factions, seeds and route difficulty',()=>{const wins={};for(const f of ['촉','위','오']){wins[f]=0;for(let i=1;i<=30;i++)if(play(i,f)==='victory')wins[f]++;for(let i=1;i<=5;i++)play(i,f,true);assert(wins[f]>0,'unwinnable faction '+f);}console.log('normal route wins / 30 with basic auto strategy:',wins);});
